export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const ERROR_MSG = 'ERROR_MSG'

export const RECEIVE_USER = 'RECEIVE_USER'

export const RESET_USER = 'RESET_USER'

export const POST_SUBMIT = 'POST_SUBMIT'

export const RECEIVE_POSTLIST = 'RECEIVE_POSTLIST'

export const RECEIVE_POST = 'RECEIVE_POST'

export const SEND_COMMENT = 'SEND_COMMENT'

export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'

export const RECEIVE_UPDATE_POST = 'RECEIVE_UPDATE_POST'

export const RECEIVE_ALL_COMMENTS = 'RECEIVE_ALL_COMMENTS' 

export const RECEIVE_DELETE_POST = 'RECEIVE_DELETE_POST' 

export const RECEIVE_DELETE_COMMENT = 'RECEIVE_DELETE_COMMENT' 